# Generated by Django 4.2.18 on 2026-06-09 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rg', models.IntegerField(help_text='Informe o RG:')),
                ('nome', models.CharField(help_text='Informe o nome:', max_length=100)),
                ('data_nascimento', models.DateField(help_text='Informe a data de nascimento:')),
                ('ddd', models.IntegerField(help_text='Informe o DDD:')),
                ('telefone', models.IntegerField(help_text='Informe o Telefone:')),
                ('codigo_titulo', models.ForeignKey(help_text='Informe o Título', null=True, on_delete=django.db.models.deletion.CASCADE, to='titulo.titulo')),
            ],
        ),
    ]
