# Generated by Django 4.2.18 on 2026-06-09 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0001_initial'),
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.ForeignKey(help_text='Informe o Título', on_delete=django.db.models.deletion.CASCADE, to='titulo.titulo'),
        ),
    ]
