# Generated by Django 4.2.18 on 2026-06-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0001_initial'),
        ('instrutor', '0002_alter_instrutor_codigo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, help_text='Informe o Título', null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulo.titulo'),
        ),
    ]
