# Generated by Django 4.2.18 on 2026-06-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do tipo de atividade:', max_length=70)),
            ],
        ),
    ]
