# Generated by Django 4.2.18 on 2026-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_aluno_monitor_aluno_data_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.AutoField(default=1, help_text='Informe a matrícula do aluno:', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_monitor',
            field=models.BooleanField(default=False, help_text='Informe se é aluno monitor:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_saida',
            field=models.DateField(blank=True, default=None, help_text='Informe a data de saída:', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(help_text='Informe o nome do aluno:', max_length=100),
        ),
    ]
