# Generated by Django 4.2.18 on 2026-06-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_remove_aluno_matricula_aluno_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.AutoField(default=0, help_text='Informe a matrícula do aluno:', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
