# Generated by Django 4.2.18 on 2026-06-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_remove_aluno_id_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateField(help_text='Informe a data de início na escola:'),
        ),
    ]
