# Generated by Django 4.2.18 on 2026-06-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_alter_aluno_data_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_monitor',
        ),
    ]
