# Generated by Django 4.2.18 on 2026-06-10 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrutor', '0002_alter_instrutor_codigo_titulo'),
        ('aluno', '0006_alter_aluno_data_matricula'),
        ('tipodeatividade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('horario_aula', models.TimeField(help_text='Informe o horário da turma:')),
                ('duracao_aula', models.IntegerField(help_text='Informe a duração da turma:')),
                ('data_inicial', models.DateField(help_text='Informe a data de inicio da turma:')),
                ('data_final', models.DateField(blank=True, help_text='Informe a data de fim da turma:', null=True)),
                ('codigo_tipo_atividade', models.ForeignKey(help_text='Informe o tipo de atividade', on_delete=django.db.models.deletion.CASCADE, to='tipodeatividade.tipoatividade')),
                ('id_instrutor', models.ForeignKey(help_text='Informe o instrutor', on_delete=django.db.models.deletion.CASCADE, to='instrutor.instrutor')),
                ('matricula_monitor', models.ForeignKey(help_text='Informe o aluno monitor', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
    ]
