# Generated by Django 4.2.18 on 2026-06-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='duracao_aula',
            field=models.PositiveIntegerField(help_text='Informe a duração da turma:'),
        ),
    ]
