# Generated by Django 4.2.18 on 2026-06-11 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0002_alter_instrutor_codigo_titulo'),
        ('aluno', '0006_alter_aluno_data_matricula'),
        ('tipodeatividade', '0001_initial'),
        ('turma', '0002_alter_turma_duracao_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo_tipo_atividade',
            field=models.ForeignKey(help_text='Informe o tipo de atividade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipodeatividade.tipoatividade'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_instrutor',
            field=models.ForeignKey(help_text='Informe o instrutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrutor.instrutor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='matricula_monitor',
            field=models.ForeignKey(help_text='Informe o aluno monitor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.aluno'),
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(help_text='Informe a data de matrícula na Turma:')),
                ('matricula_aluno', models.ForeignKey(help_text='Informe o Aluno Monitor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.aluno')),
                ('numero_turma', models.ForeignKey(help_text='Informe a Turma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='turma.turma')),
            ],
        ),
    ]
