# Generated by Django 4.2.18 on 2026-06-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_alter_aluno_data_matricula'),
        ('turma', '0003_alter_turma_codigo_tipo_atividade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ausencia', models.DateField(help_text='Informe a data de ausência na Turma:')),
                ('matricula_aluno', models.ForeignKey(help_text='Informe o Aluno Monitor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.aluno')),
                ('numero_turma', models.ForeignKey(help_text='Informe a Turma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='turma.turma')),
            ],
        ),
    ]
