# Generated by Django 4.2.18 on 2026-06-16 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0004_ausencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmaaluno',
            name='data_matricula',
            field=models.DateField(default=datetime.datetime.now, help_text='Informe a data de matrícula na Turma:'),
        ),
    ]
